name: gsv_trash
channels:
  - defaults
dependencies:
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - contourpy
  - cycler
  - docopt
  - flit-core
  - fonttools
  - freetype
  - future
  - giflib
  - intel-openmp
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libopenblas
  - libpng
  - libprotobuf
  - libtiff
  - libuv
  - libwebp
  - libwebp-base
  - llvm-openmp
  - lz4-c
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munkres
  - ncurses
  - ninja
  - ninja-base
  - numexpr
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pandas
  - pip
  - pycparser
  - pyparsing
  - python = 3.9
  - python-dateutil
  - pytorch
  - pytz
  - pyyaml
  - readline
  - seaborn
  - setuptools
  - six
  - sqlite
  - tk
  - torchmetrics
  - tqdm
  - typing_extensions
  - tzdata
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
    - absl-py
    - cachetools
    - charset-normalizer
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - idna
    - joblib
    - markdown
    - markupsafe
    - oauthlib
    - pillow
    - protobuf
    - pyasn1
    - pyasn1-modules
    - requests
    - requests-oauthlib
    - rsa
    - scikit-learn
    - scipy
    - tensorboard
    - tensorboard-data-server
    - tensorboard-plugin-wit
    - threadpoolctl
    - torch
    - torchvision
    - typing-extensions
    - urllib3
    - werkzeug